image_width: 1280
image_height: 1024
camera_name: hik
camera_matrix:
  rows: 3
  cols: 3
  data: [1811.81781,    0.     ,  733.113012,
            0.     , 1797.557349,  519.059043,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.076780, 0.085237, -0.008969, 0.002792, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1774.222384,    0.     ,  736.081359,    0.     ,
            0.     , 1784.976497,  514.284859,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
